import { BookOpen, FileText, Target, DollarSign, GraduationCap, Code2, Briefcase } from "lucide-react";
import type { TimelineItem } from "@/components/ui/radial-orbital-timeline";

// Re-export for the component's type
export type { TimelineItem };

export const timelineData: TimelineItem[] = [
  {
    id: 1,
    title: "Learn",
    date: "73 papers",
    content: "CVPR 2026 award candidate papers — abstracts, breakdowns, and key insights from computer vision research.",
    category: "Research",
    icon: BookOpen,
    relatedIds: [2, 5],
    status: "completed",
    energy: 100,
    href: "/learn",
  },
  {
    id: 2,
    title: "Results",
    date: "73 entries",
    content: "Structured analysis of each paper — methodology, datasets, metrics, and performance comparisons.",
    category: "Analysis",
    icon: GraduationCap,
    relatedIds: [1, 3],
    status: "completed",
    energy: 90,
    href: "/results",
  },
  {
    id: 3,
    title: "Plans",
    date: "Ongoing",
    content: "Drafts, decisions, and shipped plans — Hermes ↔ Krishna channel for work that needs review.",
    category: "Planning",
    icon: FileText,
    relatedIds: [2, 4, 5],
    status: "in-progress",
    energy: 70,
    href: "/plans",
  },
  {
    id: 4,
    title: "Track",
    date: "Live",
    content: "Task manager with projects, subtasks, priority, due dates, pomodoro focus timer, and analytics dashboard.",
    category: "Productivity",
    icon: Target,
    relatedIds: [3, 6],
    status: "in-progress",
    energy: 60,
    href: "/track",
  },
  {
    id: 5,
    title: "Finance",
    date: "Live",
    content: "Financial tracking and projections — income, expenses, and budget visualizations.",
    category: "Finance",
    icon: DollarSign,
    relatedIds: [1, 3],
    status: "in-progress",
    energy: 50,
    href: "https://kcfin.vercel.app",
  },
  {
    id: 6,
    title: "Habits",
    date: "Beta",
    content: "Habit tracker with check-ins, streaks, consistency insights, heatmap, and reminders. Cloud-synced.",
    category: " Wellness",
    icon: Code2,
    relatedIds: [4],
    status: "pending",
    energy: 30,
    href: "https://antholic.vercel.app",
  },
  {
    id: 7,
    title: "Portfolio",
    date: "2026",
    content: "Personal portfolio — projects, experience, and skills. The public face of Krishna's work.",
    category: "Profile",
    icon: Briefcase,
    relatedIds: [1, 2],
    status: "pending",
    energy: 20,
    href: "/",
  },
];